POST http://localhost:8080/wsec1e1

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
				  xmlns:gs="http://spring.io/guides/gs-producing-web-service">
   <soapenv:Header/>
   <soapenv:Body>
      <gs:getSemanaRequest>
         <gs:name>Domingo</gs:name>
      </gs:getSemanaRequest>
   </soapenv:Body>
</soapenv:Envelope>



